### ISSUE TITLE
false postive when old kernel data is present

### ISSUE THREAD

**Issue by mapietru** [bashclub/checkmk-monitoring-plugins#1]
Hello, just wanted to pinpoint the 'old kernel problematic'...

dpkg --get-selections | grep pve-kernel-5.4 | grep -v deinstall

pve-kernel-5.4.101-1-pve                        install
pve-kernel-5.4.103-1-pve                        install
pve-kernel-5.4.106-1-pve                        install
pve-kernel-5.4.114-1-pve                        install
pve-kernel-5.4.119-1-pve                        install
pve-kernel-5.4.124-1-pve                        install
pve-kernel-5.4.73-1-pve                         install
pve-kernel-5.4.78-2-pve                         install
pve-kernel-5.4.98-1-pve                         install

when piping the putput thru "tail -1 | cut -f1 | cut -d'-' -f3-"
I got "5.4.98-1-pve" which is not the latest installed kernel, as the version
is not sorted by the latest install, due to non-leading zero.

1 "Running Kernel" version_ok=1;1;|running_kernel=5.4.124-1-pve;;|latest_installed_kernel=5.4.98-1-pve;; Newer Kernel version installed. Please reboot machine! - WARN

Best regards,
Markus

**Comment by 47k** [comment]
I have the same issues: 

**Buster**
linux-image-4.19.0-17-amd64			install
linux-image-4.19.0-18-amd64			install (Active)

0 "Running Kernel" version_ok=0;1;|running_kernel=4.19.0-18-amd64;;|latest_installed_kernel=4.19.0-18-amd64;; Currently running Kernel up-to-date - OK

**Bullseye**
linux-image-5.10.0-10-amd64			install (Active)
linux-image-5.10.0-9-amd64			install

1 "Running Kernel" version_ok=1;1;|running_kernel=5.10.0-10-amd64;;|latest_installed_kernel=5.10.0-9-amd64;; Newer Kernel version installed. Please reboot machine! - WARN
